### ISSUE TITLE
unable to make application

### ISSUE THREAD

**Issue by azalea666** [dkessner/processing-p5-convert#4]
the make command gives errors and no executable is produced -- can this be updated to run currently? it would be very useful to me.
here is output of make

`processing-p5-convert % make
updating node_modules
npm install
npm WARN package.json processing-p5-convert@1.0.0 No repository field.
npm WARN deprecated babel-preset-es2015@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read https://babeljs.io/env to update!
npm WARN engine prettier@2.3.1: wanted: {"node":">=10.13.0"} (current: {"node":"0.12.0","npm":"2.5.1"})
npm WARN deprecated core-js@2.6.12: core-js@<3.23.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Some versions have web compatibility issues. Please, upgrade your dependencies to the actual version of core-js.
/
> core-js@2.6.12 postinstall /Users/[user]/Documents/processing-p5-convert/node_modules/babel-core/node_modules/babel-register/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"

> core-js@2.6.12 postinstall /Users/[user]/Documents/processing-p5-convert/node_modules/babel-preset-es2015/node_modules/babel-plugin-transform-es2015-function-name/node_modules/babel-runtime/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"

> core-js@2.6.12 postinstall /Users/[user]/Documents/processing-p5-convert/node_modules/babel-preset-es2015/node_modules/babel-plugin-transform-es2015-modules-amd/node_modules/babel-runtime/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"

> core-js@2.6.12 postinstall /Users/[user]/Documents/processing-p5-convert/node_modules/babel-preset-es2015/node_modules/babel-plugin-transform-es2015-sticky-regex/node_modules/babel-runtime/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"

> core-js@2.6.12 postinstall /Users/[user]/Documents/processing-p5-convert/node_modules/babel-preset-es2015/node_modules/babel-plugin-transform-es2015-duplicate-keys/node_modules/babel-runtime/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"

> core-js@2.6.12 postinstall /Users/[user]/Documents/processing-p5-convert/node_modules/babel-preset-stage-3/node_modules/babel-plugin-transform-exponentiation-operator/node_modules/babel-runtime/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"

> core-js@2.6.12 postinstall /Users/[user]/Documents/processing-p5-convert/node_modules/babel-preset-es2015/node_modules/babel-plugin-transform-es2015-arrow-functions/node_modules/babel-runtime/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"

> core-js@2.6.12 postinstall /Users/[user]/Documents/processing-p5-convert/node_modules/babel-preset-es2015/node_modules/babel-plugin-transform-es2015-spread/node_modules/babel-runtime/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"

> core-js@2.6.12 postinstall /Users/[user]/Documents/processing-p5-convert/node_modules/babel-preset-es2015/node_modules/babel-plugin-transform-es2015-modules-umd/node_modules/babel-runtime/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"

> core-js@2.6.12 postinstall /Users/[user]/Documents/processing-p5-convert/node_modules/babel-preset-es2015/node_modules/babel-plugin-transform-es2015-block-scoped-functions/node_modules/babel-runtime/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"

> core-js@2.6.12 postinstall /Users/[user]/Documents/processing-p5-convert/node_modules/babel-preset-stage-3/node_modules/babel-plugin-transform-async-generator-functions/node_modules/babel-runtime/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"

> core-js@2.6.12 postinstall /Users/[user]/Documents/processing-p5-convert/node_modules/babel-preset-stage-3/node_modules/babel-plugin-transform-async-to-generator/node_modules/babel-runtime/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"

> core-js@2.6.12 postinstall /Users/[user]/Documents/processing-p5-convert/node_modules/babel-preset-es2015/node_modules/babel-plugin-check-es2015-constants/node_modules/babel-runtime/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"

> core-js@2.6.12 postinstall /Users/[user]/Documents/processing-p5-convert/node_modules/babel-preset-es2015/node_modules/babel-plugin-transform-es2015-literals/node_modules/babel-runtime/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"

> core-js@2.6.12 postinstall /Users/[user]/Documents/processing-p5-convert/node_modules/babel-preset-es2015/node_modules/babel-plugin-transform-es2015-object-super/node_modules/babel-runtime/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"

> core-js@2.6.12 postinstall /Users/[user]/Documents/processing-p5-convert/node_modules/babel-preset-es2015/node_modules/babel-plugin-transform-es2015-computed-properties/node_modules/babel-runtime/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"

> core-js@2.6.12 postinstall /Users/[user]/Documents/processing-p5-convert/node_modules/babel-preset-stage-3/node_modules/babel-plugin-transform-object-rest-spread/node_modules/babel-runtime/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"

> core-js@2.6.12 postinstall /Users/[user]/Documents/processing-p5-convert/node_modules/babel-preset-es2015/node_modules/babel-plugin-transform-es2015-template-literals/node_modules/babel-runtime/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"

> core-js@2.6.12 postinstall /Users/[user]/Documents/processing-p5-convert/node_modules/babel-preset-es2015/node_modules/babel-plugin-transform-es2015-shorthand-properties/node_modules/babel-runtime/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"

> core-js@2.6.12 postinstall /Users/[user]/Documents/processing-p5-convert/node_modules/babel-preset-es2015/node_modules/babel-plugin-transform-es2015-typeof-symbol/node_modules/babel-runtime/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"

> core-js@2.6.12 postinstall /Users/[user]/Documents/processing-p5-convert/node_modules/babel-preset-es2015/node_modules/babel-plugin-transform-es2015-unicode-regex/node_modules/babel-runtime/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"

> core-js@2.6.12 postinstall /Users/[user]/Documents/processing-p5-convert/node_modules/babel-preset-es2015/node_modules/babel-plugin-transform-es2015-for-of/node_modules/babel-runtime/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"

> core-js@2.6.12 postinstall /Users/[user]/Documents/processing-p5-convert/node_modules/babel-preset-es2015/node_modules/babel-plugin-transform-es2015-destructuring/node_modules/babel-runtime/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"

> core-js@2.6.12 postinstall /Users/[user]/Documents/processing-p5-convert/node_modules/babel-preset-es2015/node_modules/babel-plugin-transform-es2015-modules-systemjs/node_modules/babel-runtime/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"

> core-js@2.6.12 postinstall /Users/[user]/Documents/processing-p5-convert/node_modules/babel-preset-es2015/node_modules/babel-plugin-transform-es2015-modules-commonjs/node_modules/babel-runtime/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"

> core-js@2.6.12 postinstall /Users/[user]/Documents/processing-p5-convert/node_modules/babel-preset-es2015/node_modules/babel-plugin-transform-es2015-block-scoping/node_modules/babel-runtime/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"

> core-js@2.6.12 postinstall /Users/[user]/Documents/processing-p5-convert/node_modules/babel-preset-es2015/node_modules/babel-plugin-transform-es2015-classes/node_modules/babel-runtime/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"

> core-js@2.6.12 postinstall /Users/[user]/Documents/processing-p5-convert/node_modules/babel-preset-es2015/node_modules/babel-plugin-transform-es2015-parameters/node_modules/babel-runtime/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"

> core-js@2.6.12 postinstall /Users/[user]/Documents/processing-p5-convert/node_modules/babel-preset-env/node_modules/babel-plugin-transform-es2015-arrow-functions/node_modules/babel-runtime/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"

> core-js@2.6.12 postinstall /Users/[user]/Documents/processing-p5-convert/node_modules/babel-preset-env/node_modules/babel-plugin-transform-es2015-modules-amd/node_modules/babel-runtime/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"

> core-js@2.6.12 postinstall /Users/[user]/Documents/processing-p5-convert/node_modules/babel-preset-env/node_modules/babel-plugin-transform-es2015-duplicate-keys/node_modules/babel-runtime/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"

> core-js@2.6.12 postinstall /Users/[user]/Documents/processing-p5-convert/node_modules/babel-preset-env/node_modules/babel-plugin-transform-es2015-typeof-symbol/node_modules/babel-runtime/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"

> core-js@2.6.12 postinstall /Users/[user]/Documents/processing-p5-convert/node_modules/babel-preset-env/node_modules/babel-plugin-transform-es2015-block-scoped-functions/node_modules/babel-runtime/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"

> core-js@2.6.12 postinstall /Users/[user]/Documents/processing-p5-convert/node_modules/babel-preset-env/node_modules/babel-plugin-transform-es2015-function-name/node_modules/babel-runtime/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"

> core-js@2.6.12 postinstall /Users/[user]/Documents/processing-p5-convert/node_modules/babel-preset-env/node_modules/babel-plugin-transform-es2015-unicode-regex/node_modules/babel-runtime/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"

> core-js@2.6.12 postinstall /Users/[user]/Documents/processing-p5-convert/node_modules/babel-preset-env/node_modules/babel-plugin-transform-exponentiation-operator/node_modules/babel-runtime/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"

> core-js@2.6.12 postinstall /Users/[user]/Documents/processing-p5-convert/node_modules/babel-preset-env/node_modules/babel-plugin-transform-async-to-generator/node_modules/babel-runtime/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"

> core-js@2.6.12 postinstall /Users/[user]/Documents/processing-p5-convert/node_modules/babel-preset-env/node_modules/babel-plugin-transform-es2015-sticky-regex/node_modules/babel-runtime/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"

> core-js@2.6.12 postinstall /Users/[user]/Documents/processing-p5-convert/node_modules/babel-preset-env/node_modules/babel-plugin-transform-es2015-modules-umd/node_modules/babel-runtime/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"

> core-js@2.6.12 postinstall /Users/[user]/Documents/processing-p5-convert/node_modules/babel-preset-env/node_modules/babel-plugin-transform-es2015-object-super/node_modules/babel-runtime/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"

> core-js@2.6.12 postinstall /Users/[user]/Documents/processing-p5-convert/node_modules/babel-preset-env/node_modules/babel-plugin-transform-es2015-shorthand-properties/node_modules/babel-runtime/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"

> core-js@2.6.12 postinstall /Users/[user]/Documents/processing-p5-convert/node_modules/babel-preset-env/node_modules/babel-plugin-check-es2015-constants/node_modules/babel-runtime/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"

> core-js@2.6.12 postinstall /Users/[user]/Documents/processing-p5-convert/node_modules/babel-preset-env/node_modules/babel-plugin-transform-es2015-spread/node_modules/babel-runtime/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"

> core-js@2.6.12 postinstall /Users/[user]/Documents/processing-p5-convert/node_modules/babel-preset-env/node_modules/babel-plugin-transform-es2015-computed-properties/node_modules/babel-runtime/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"

> core-js@2.6.12 postinstall /Users/[user]/Documents/processing-p5-convert/node_modules/babel-preset-env/node_modules/babel-plugin-transform-es2015-modules-systemjs/node_modules/babel-runtime/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"

> core-js@2.6.12 postinstall /Users/[user]/Documents/processing-p5-convert/node_modules/babel-preset-env/node_modules/babel-plugin-transform-es2015-destructuring/node_modules/babel-runtime/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"

> core-js@2.6.12 postinstall /Users/[user]/Documents/processing-p5-convert/node_modules/babel-preset-env/node_modules/babel-plugin-transform-es2015-for-of/node_modules/babel-runtime/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"

> core-js@2.6.12 postinstall /Users/[user]/Documents/processing-p5-convert/node_modules/babel-preset-env/node_modules/babel-plugin-transform-es2015-literals/node_modules/babel-runtime/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"

> core-js@2.6.12 postinstall /Users/[user]/Documents/processing-p5-convert/node_modules/babel-preset-env/node_modules/babel-plugin-transform-es2015-template-literals/node_modules/babel-runtime/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"

> core-js@2.6.12 postinstall /Users/[user]/Documents/processing-p5-convert/node_modules/babel-preset-env/node_modules/babel-plugin-transform-es2015-modules-commonjs/node_modules/babel-runtime/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"

> core-js@2.6.12 postinstall /Users/[user]/Documents/processing-p5-convert/node_modules/babel-preset-env/node_modules/babel-plugin-transform-es2015-parameters/node_modules/babel-runtime/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"

> core-js@2.6.12 postinstall /Users/[user]/Documents/processing-p5-convert/node_modules/babel-preset-env/node_modules/babel-plugin-transform-es2015-block-scoping/node_modules/babel-runtime/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"

> core-js@2.6.12 postinstall /Users/[user]/Documents/processing-p5-convert/node_modules/babel-preset-env/node_modules/babel-plugin-transform-es2015-classes/node_modules/babel-runtime/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"

> core-js@2.6.12 postinstall /Users/[user]/Documents/processing-p5-convert/node_modules/babel-core/node_modules/babel-runtime/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"

> core-js@2.6.12 postinstall /Users/[user]/Documents/processing-p5-convert/node_modules/babel-preset-es2015/node_modules/babel-plugin-transform-regenerator/node_modules/regenerator-transform/node_modules/babel-runtime/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"

> core-js@2.6.12 postinstall /Users/[user]/Documents/processing-p5-convert/node_modules/babel-preset-env/node_modules/babel-plugin-transform-regenerator/node_modules/regenerator-transform/node_modules/babel-runtime/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"

fs@0.0.1-security node_modules/fs

babelify@8.0.0 node_modules/babelify

prettier-plugin-java@1.6.2 node_modules/prettier-plugin-java
├── java-parser@2.0.2 (chevrotain@6.5.0)
└── lodash@4.17.21

java-parser@1.4.0 node_modules/java-parser
├── chevrotain@6.5.0 (regexp-to-ast@0.4.0)
└── lodash@4.17.21

prettier@2.3.1 node_modules/prettier

babel-preset-stage-3@6.24.1 node_modules/babel-preset-stage-3
├── babel-plugin-syntax-trailing-function-commas@6.22.0
├── babel-plugin-transform-exponentiation-operator@6.24.1 (babel-plugin-syntax-exponentiation-operator@6.13.0, babel-helper-builder-binary-assignment-operator-visitor@6.24.1, babel-runtime@6.26.0)
├── babel-plugin-transform-async-generator-functions@6.24.1 (babel-plugin-syntax-async-generators@6.13.0, babel-helper-remap-async-to-generator@6.24.1, babel-runtime@6.26.0)
├── babel-plugin-transform-async-to-generator@6.24.1 (babel-plugin-syntax-async-functions@6.13.0, babel-helper-remap-async-to-generator@6.24.1, babel-runtime@6.26.0)
└── babel-plugin-transform-object-rest-spread@6.26.0 (babel-plugin-syntax-object-rest-spread@6.13.0, babel-runtime@6.26.0)

babel-core@6.26.3 node_modules/babel-core
├── slash@1.0.0
├── path-is-absolute@1.0.1
├── babel-messages@6.23.0
├── babel-template@6.26.0
├── convert-source-map@1.9.0
├── private@0.1.8
├── babel-helpers@6.24.1
├── json5@0.5.1
├── debug@2.6.9 (ms@2.0.0)
├── minimatch@3.1.2 (brace-expansion@1.1.11)
├── babel-code-frame@6.26.0 (js-tokens@3.0.2, esutils@2.0.3, chalk@1.1.3)
├── babylon@6.18.0
├── babel-types@6.26.0 (to-fast-properties@1.0.3, esutils@2.0.3)
├── babel-generator@6.26.1 (trim-right@1.0.1, jsesc@1.3.0, detect-indent@4.0.0)
├── babel-traverse@6.26.0 (globals@9.18.0, invariant@2.2.4)
├── source-map@0.5.7
├── lodash@4.17.21
├── babel-register@6.26.0 (home-or-tmp@2.0.0, source-map-support@0.4.18, mkdirp@0.5.6, core-js@2.6.12)
└── babel-runtime@6.26.0 (regenerator-runtime@0.11.1, core-js@2.6.12)

babel-preset-es2015@6.24.1 node_modules/babel-preset-es2015
├── babel-plugin-transform-es2015-function-name@6.24.1 (babel-types@6.26.0, babel-helper-function-name@6.24.1, babel-runtime@6.26.0)
├── babel-plugin-transform-es2015-modules-amd@6.24.1 (babel-template@6.26.0, babel-runtime@6.26.0)
├── babel-plugin-transform-es2015-sticky-regex@6.24.1 (babel-helper-regex@6.26.0, babel-types@6.26.0, babel-runtime@6.26.0)
├── babel-plugin-transform-es2015-duplicate-keys@6.24.1 (babel-types@6.26.0, babel-runtime@6.26.0)
├── babel-plugin-transform-es2015-arrow-functions@6.22.0 (babel-runtime@6.26.0)
├── babel-plugin-transform-es2015-spread@6.22.0 (babel-runtime@6.26.0)
├── babel-plugin-transform-es2015-modules-umd@6.24.1 (babel-template@6.26.0, babel-runtime@6.26.0)
├── babel-plugin-transform-es2015-block-scoped-functions@6.22.0 (babel-runtime@6.26.0)
├── babel-plugin-check-es2015-constants@6.22.0 (babel-runtime@6.26.0)
├── babel-plugin-transform-es2015-literals@6.22.0 (babel-runtime@6.26.0)
├── babel-plugin-transform-es2015-object-super@6.24.1 (babel-helper-replace-supers@6.24.1, babel-runtime@6.26.0)
├── babel-plugin-transform-es2015-computed-properties@6.24.1 (babel-template@6.26.0, babel-runtime@6.26.0)
├── babel-plugin-transform-es2015-template-literals@6.22.0 (babel-runtime@6.26.0)
├── babel-plugin-transform-es2015-shorthand-properties@6.24.1 (babel-types@6.26.0, babel-runtime@6.26.0)
├── babel-plugin-transform-es2015-typeof-symbol@6.23.0 (babel-runtime@6.26.0)
├── babel-plugin-transform-es2015-unicode-regex@6.24.1 (regexpu-core@2.0.0, babel-helper-regex@6.26.0, babel-runtime@6.26.0)
├── babel-plugin-transform-es2015-for-of@6.23.0 (babel-runtime@6.26.0)
├── babel-plugin-transform-es2015-destructuring@6.23.0 (babel-runtime@6.26.0)
├── babel-plugin-transform-es2015-modules-systemjs@6.24.1 (babel-template@6.26.0, babel-helper-hoist-variables@6.24.1, babel-runtime@6.26.0)
├── babel-plugin-transform-es2015-modules-commonjs@6.26.2 (babel-plugin-transform-strict-mode@6.24.1, babel-template@6.26.0, babel-types@6.26.0, babel-runtime@6.26.0)
├── babel-plugin-transform-es2015-block-scoping@6.26.0 (babel-types@6.26.0, babel-template@6.26.0, babel-traverse@6.26.0, lodash@4.17.21, babel-runtime@6.26.0)
├── babel-plugin-transform-es2015-classes@6.24.1 (babel-helper-optimise-call-expression@6.24.1, babel-messages@6.23.0, babel-helper-replace-supers@6.24.1, babel-helper-function-name@6.24.1, babel-helper-define-map@6.26.0, babel-template@6.26.0, babel-types@6.26.0, babel-traverse@6.26.0, babel-runtime@6.26.0)
├── babel-plugin-transform-es2015-parameters@6.24.1 (babel-helper-get-function-arity@6.24.1, babel-helper-call-delegate@6.24.1, babel-template@6.26.0, babel-types@6.26.0, babel-traverse@6.26.0, babel-runtime@6.26.0)
└── babel-plugin-transform-regenerator@6.26.0 (regenerator-transform@0.10.1)

babel-preset-env@1.7.0 node_modules/babel-preset-env
├── babel-plugin-syntax-trailing-function-commas@6.22.0
├── semver@5.7.2
├── invariant@2.2.4 (loose-envify@1.4.0)
├── browserslist@3.2.8 (electron-to-chromium@1.4.754, caniuse-lite@1.0.30001615)
├── babel-plugin-transform-es2015-arrow-functions@6.22.0 (babel-runtime@6.26.0)
├── babel-plugin-transform-es2015-modules-amd@6.24.1 (babel-template@6.26.0, babel-runtime@6.26.0)
├── babel-plugin-transform-es2015-duplicate-keys@6.24.1 (babel-types@6.26.0, babel-runtime@6.26.0)
├── babel-plugin-transform-es2015-typeof-symbol@6.23.0 (babel-runtime@6.26.0)
├── babel-plugin-transform-es2015-block-scoped-functions@6.22.0 (babel-runtime@6.26.0)
├── babel-plugin-transform-es2015-function-name@6.24.1 (babel-types@6.26.0, babel-helper-function-name@6.24.1, babel-runtime@6.26.0)
├── babel-plugin-transform-es2015-unicode-regex@6.24.1 (regexpu-core@2.0.0, babel-helper-regex@6.26.0, babel-runtime@6.26.0)
├── babel-plugin-transform-exponentiation-operator@6.24.1 (babel-plugin-syntax-exponentiation-operator@6.13.0, babel-helper-builder-binary-assignment-operator-visitor@6.24.1, babel-runtime@6.26.0)
├── babel-plugin-transform-async-to-generator@6.24.1 (babel-plugin-syntax-async-functions@6.13.0, babel-helper-remap-async-to-generator@6.24.1, babel-runtime@6.26.0)
├── babel-plugin-transform-es2015-sticky-regex@6.24.1 (babel-helper-regex@6.26.0, babel-types@6.26.0, babel-runtime@6.26.0)
├── babel-plugin-transform-es2015-modules-umd@6.24.1 (babel-template@6.26.0, babel-runtime@6.26.0)
├── babel-plugin-transform-es2015-object-super@6.24.1 (babel-helper-replace-supers@6.24.1, babel-runtime@6.26.0)
├── babel-plugin-transform-es2015-shorthand-properties@6.24.1 (babel-types@6.26.0, babel-runtime@6.26.0)
├── babel-plugin-check-es2015-constants@6.22.0 (babel-runtime@6.26.0)
├── babel-plugin-transform-es2015-spread@6.22.0 (babel-runtime@6.26.0)
├── babel-plugin-transform-es2015-computed-properties@6.24.1 (babel-template@6.26.0, babel-runtime@6.26.0)
├── babel-plugin-transform-es2015-modules-systemjs@6.24.1 (babel-template@6.26.0, babel-helper-hoist-variables@6.24.1, babel-runtime@6.26.0)
├── babel-plugin-transform-es2015-destructuring@6.23.0 (babel-runtime@6.26.0)
├── babel-plugin-transform-es2015-for-of@6.23.0 (babel-runtime@6.26.0)
├── babel-plugin-transform-es2015-literals@6.22.0 (babel-runtime@6.26.0)
├── babel-plugin-transform-es2015-template-literals@6.22.0 (babel-runtime@6.26.0)
├── babel-plugin-transform-es2015-modules-commonjs@6.26.2 (babel-plugin-transform-strict-mode@6.24.1, babel-template@6.26.0, babel-types@6.26.0, babel-runtime@6.26.0)
├── babel-plugin-transform-es2015-parameters@6.24.1 (babel-helper-get-function-arity@6.24.1, babel-helper-call-delegate@6.24.1, babel-template@6.26.0, babel-types@6.26.0, babel-traverse@6.26.0, babel-runtime@6.26.0)
├── babel-plugin-transform-es2015-block-scoping@6.26.0 (babel-types@6.26.0, babel-template@6.26.0, babel-traverse@6.26.0, lodash@4.17.21, babel-runtime@6.26.0)
├── babel-plugin-transform-es2015-classes@6.24.1 (babel-helper-optimise-call-expression@6.24.1, babel-messages@6.23.0, babel-helper-replace-supers@6.24.1, babel-helper-function-name@6.24.1, babel-helper-define-map@6.26.0, babel-template@6.26.0, babel-types@6.26.0, babel-traverse@6.26.0, babel-runtime@6.26.0)
└── babel-plugin-transform-regenerator@6.26.0 (regenerator-transform@0.10.1)
updating minimal example
running tests
test: hello
/Users/[user]/Documents/processing-p5-convert/js/ppconvert.js:22
import { 
^^^^^^
SyntaxError: Unexpected reserved word
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
0a1,12
> //
> // hello
> //
> function setup() {
>     createCanvas(400, 400);
> }
> function draw() {
>     background(0);
>     fill("#00ff00"); // Processing color literal
>     ellipse(200, 200, 100, 100);
> }
> 
make: *** [hello.test] Error 1
`

**Comment by azalea666** [comment]
i just needed to update install of node. never mind. sorry.
